export default {
  content: {
    backgroundColor: '#000000',
    flex: 1,
  },
  emptyContent: {
    backgroundColor: '#ffffff',
    flex: 1,
  },
  emptyContainer: {
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  },
  emptyMsg: {
    color: '#777',
    fontSize: 18,
    textAlign: 'center',
    alignSelf: 'center',
  },
  drawerIcon: {
    width: 30,
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 2,
  },
  button: {
    borderWidth: 1,
    borderColor: '#000',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 2,
    flexDirection: 'row',
  },
  btnText: {
    fontWeight: 'bold',
    fontSize: 14,
  },
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#000000',
  },
  paragraph: {
    flex: 1,
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'center',
    color: '#ffffff',
    marginLeft: -30,
    zIndex: -1,
  },
  scanSquare: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
  },
  containerView: {
    paddingHorizontal: 10,
    marginTop: 20,
    flexDirection: 'row',
    alignContent: 'center',
    justifyContent: 'center',
    backgroundColor: '#000000',
    height: 50,
    alignItems: 'center',
  },
  backImage: {
    height: 30,
    width: 30,
  },
};
